from __future__ import annotations
import argparse,json
from pathlib import Path

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--split-a',required=True); ap.add_argument('--split-b',required=True); ap.add_argument('--calibration-report',required=True); ap.add_argument('--fit-report',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
 A=json.load(open(a.split_a)); B=json.load(open(a.split_b)); C=json.load(open(a.calibration_report)); F=json.load(open(a.fit_report)); eng=bool(A.get('engineering_valid') and B.get('engineering_valid')); train=bool(F.get('train_gate_pass') and F.get('nested_crossfit',{}).get('fold_pass_count')==5); cal=bool(C.get('calibration_total_scene_count')==500 and int(C.get('selected_policy_proposal_count',0))>=64 and abs(float(C.get('alpha',0))-.05)<=1e-12); both=bool(eng and train and cal and A.get('full_split_pass') and B.get('full_split_pass'))
 conclusion='SPCR_incumbent_augmented_selection_consistent_ordering_plus_selected_policy_calibration_reproduces_on_double_fresh' if both else ('engineering_invalid_stop' if not eng else 'SPCR_not_promoted_current_frozen_mechanism_fails_at_least_one_independent_gate_or_block'); nxt='freeze_and_run_one_independent_full_validation_reproduction' if both else 'STOP_do_not_pool_AB_or_sweep_lambda_alpha_thresholds_use_failure_slice_to_choose_next_mechanism'; rep={'audit':'v64_3_33_eaf_icer_spcr_double_fresh_screen','engineering_valid_both':eng,'train_nested_full_mechanism_gate_pass':train,'independent_calibration_valid':cal,'double_fresh_promotion_pass':both,'scientific_conclusion':conclusion,'next_action':nxt,'train_fit':F,'independent_calibration':C,'split_A':A,'split_B':B,'protocol':'Paired V32.1 failure prerequisite -> nested TRAIN structured selector + selected-policy calibration gate -> independent CAL500 selected-policy calibration -> untouched A500/B500 judged separately. No pooled rescue.'}; Path(a.output).write_text(json.dumps(rep,indent=2,sort_keys=True)+'\n'); print(json.dumps({'pass':both,'engineering':eng,'train':train,'calibration':cal,'conclusion':conclusion,'next_action':nxt},sort_keys=True))
if __name__=='__main__': main()
