from __future__ import annotations
import argparse,json
from pathlib import Path

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--split-a-report',required=True); ap.add_argument('--split-b-report',required=True); ap.add_argument('--train-fit-report',required=True); ap.add_argument('--output',required=True); a=ap.parse_args()
    A=json.load(open(a.split_a_report)); B=json.load(open(a.split_b_report)); tr=json.load(open(a.train_fit_report))
    train=bool(tr.get('train_gate_pass',False)); both=bool(A.get('full_split_pass') and B.get('full_split_pass')); signal=bool(A.get('endpoint_strict_signal_over_V25_DRC') or B.get('endpoint_strict_signal_over_V25_DRC')); promote=bool(train and both and signal)
    if promote: nxt='freeze_V30_PCWER_and_run_one_independent_full_val_reproduction_before_test_or_closed_loop'
    elif not train: nxt='TRAIN_gate_invalid_stop_before_spending_or_interpreting_fresh'
    elif not both: nxt='PCWER_not_independently_reproduced_stop_do_not_tune_B_witness_weights_DRC_K_or_threshold'
    else: nxt='mechanism_reproduced_without_endpoint_signal_stop_before_full_val'
    r={'audit':'v64_3_30_eaf_icer_pcwer_double_fresh_screen','train_gate_pass':train,'train_catastrophe_free':bool(tr.get('proposal_locked_drc_crossfit',{}).get('all_folds_catastrophe_free',False)),'split_A_pass':bool(A.get('full_split_pass')),'split_B_pass':bool(B.get('full_split_pass')),'both_independent_blocks_pass':both,'pcwer_contract_both':bool(A.get('pcwer_contract') and B.get('pcwer_contract')),'proposal_lock_control_contract_both':bool(A.get('proposal_lock_control_contract') and B.get('proposal_lock_control_contract')),'safe_coverage_gain_vs_lock_both':bool(A.get('safe_recovery_coverage_gain_over_lock_control') and B.get('safe_recovery_coverage_gain_over_lock_control')),'coverage_not_below_V25_both':bool(A.get('safe_recovery_coverage_not_below_V25_DRC') and B.get('safe_recovery_coverage_not_below_V25_DRC')),'catastrophe_free_both':bool(A.get('selected_replacement_catastrophe_free') and B.get('selected_replacement_catastrophe_free')),'tail_noninferior_to_V25_both':bool(A.get('selected_tail_noninferior_to_V25_DRC') and B.get('selected_tail_noninferior_to_V25_DRC')),'endpoint_noninferior_both':bool(A.get('endpoint_noninferior_to_V25_DRC') and B.get('endpoint_noninferior_to_V25_DRC')),'endpoint_strict_signal_at_least_one_block':signal,'full_promotion_to_independent_full_val_reproduction':promote,'test_or_closed_loop_allowed':False,'next_action':nxt,'split_A_next_action':A.get('next_action'),'split_B_next_action':B.get('next_action'),'interpretation':'V30 tests operator-conditioned decision-evidence sufficiency at fixed B=16. The lock-only DRC arm separates same-proposal/no-fallback effects from PCWER evidence rebinding. Promotion requires catastrophe-free TRAIN folds plus independent A/B safe-coverage gain over that operator control without falling below historical V25 coverage or tail/endpoint safety.'}
    out=Path(a.output);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(json.dumps(r,indent=2,sort_keys=True));print(json.dumps(r,indent=2,sort_keys=True))
if __name__=='__main__':main()
